name: Actions

on: [push]

jobs:
  laravel:
    name: Laravel (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.*'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug #optional
      - name: Start mysql service
        run: sudo cat /etc/mysql/debian.cnf
      - name: login mysql
        run: mysql -u debian-sys-maint -p
      - name: login mysql 1
        run: use mysql;
      - name: login mysql 2
        run: UPDATE user SET plugin='mysql_native_password' WHERE User='root';
      - name: lognn 3
        run: update user set authentication_string=PASSWORD("mysql") where User='root';
      - name: kignug 34
        run: ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql';
      - name: gdgdgd
        run: flush privileges;
      - name: ggg
        run: exit;
      - name: fsfsf
        run: mysql -u root -p
      - uses: actions/checkout@v1
      - name: Run composer install
        run: composer install
      - name: Run npm install
        run: npm install
      - name: Run npm run dev
        run: npm run dev
      - name: Create .env
        run: cp .env.example .env
      - name: Create app key
        run: php artisan key:generate
      - name: Run migrations
        run: php artisan migrate
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing
